version: 2

build:
  image: latest
  apt_packages:
    - graphviz

python:
  version: 3.11
  system_packages: false
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - test

formats: []
