name: marxs

channels:
    - astropy

dependencies:
    - python>=3.7
    - astropy
    - Cython
    - cffi
    - matplotlib
    - numpy
    - sphinx-astropy
    - jsonschema
    - pyyaml
    - scipy
    - pip:
        - transforms3d